spring:
  redis:
    host: 192.168.6.44
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.ld.entity
logging:
  level:
    com:
      ld:
        mapper: debug