spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/html/
#    suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.ld.entity
